package simpleDistribute;

import com.formdev.flatlaf.FlatDarkLaf;
import com.lowagie.text.Chunk;
import java.awt.Color;
import com.lowagie.text.Paragraph;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;


public class BulkDispacth extends javax.swing.JFrame {
    
    private final DbCon con = new DbCon();
    private final Date date = new Date();

    public BulkDispacth() {
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnGenerateReport = new javax.swing.JButton();
        progressbar = new javax.swing.JProgressBar();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txt_firstOrderNo = new javax.swing.JTextField();
        txt_lastOrderNo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Day Report");
        setAlwaysOnTop(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Dispach and Report");

        btnGenerateReport.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnGenerateReport.setText("Dispatch & Generate PDF");
        btnGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReportActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("From");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("To");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Order Numbers Range");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setRows(2);
        jTextArea1.setText("* Please enter all finalized invoices belongs to \nproformas of last destibution before generate\nreport.");
        jScrollPane1.setViewportView(jTextArea1);

        txt_firstOrderNo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_firstOrderNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_firstOrderNoKeyPressed(evt);
            }
        });

        txt_lastOrderNo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progressbar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_firstOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_lastOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(btnGenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(txt_firstOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lastOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnGenerateReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressbar, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportActionPerformed
        try {
            pdf();
        } catch (SQLException | IOException ex) {
            Logger.getLogger(BulkDispacth.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGenerateReportActionPerformed

    private void txt_firstOrderNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_firstOrderNoKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            txt_lastOrderNo.requestFocus();
        }
    }//GEN-LAST:event_txt_firstOrderNoKeyPressed

    public static void main(String args[]) {
        try {
            FlatDarkLaf.setup();
        } catch (Exception e) {
            System.out.println("Theme Setup Error: " + e);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BulkDispacth().setVisible(true);
            }
        });
    }
    
    public void pdf() throws SQLException, IOException{
        try {
            progressbar.setValue(5);
            
            String firstOrderNo = txt_firstOrderNo.getText();
            String lastOrderNo = txt_lastOrderNo.getText();
            
            progressbar.setValue(10);
            long msec = date.getTime();
            String fileName = "Dispach_Summery "+msec;
            String DEST = "./Reports/Dispatch/"+fileName+".pdf";
            PdfWriter writer;
            try (Document doc = new Document()) {
                writer = PdfWriter.getInstance(doc, new FileOutputStream(DEST));
                //setting font family, color
                Font fontTopic = new Font(Font.HELVETICA, 13, Font.BOLDITALIC, Color.RED);
                Font fontTblHead = new Font(Font.HELVETICA, 7, Font.BOLDITALIC);
                Font fontTblData = new Font(Font.HELVETICA, 9, Font.NORMAL);
                doc.open();
                //Add Content
                Paragraph topic = new Paragraph("Dispatch Summery Report", fontTopic);
                topic.setAlignment(Element.ALIGN_CENTER);
                topic.getFont().setStyle(Font.UNDERLINE);
                doc.add(topic);
                progressbar.setValue(15);
                
                SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                var dt = new Paragraph("Date: "+String.valueOf(formatter.format(date)),fontTblData);
                dt.setAlignment(Element.ALIGN_LEFT);
                doc.add(dt);
                
                //Blank Line
                doc.add( Chunk.NEWLINE );
                
                //Table
                PdfPTable table = new PdfPTable(4);
                table.setWidthPercentage(80);
                // setting column widths
                table.setWidths(new float[] {3, 1, 1, 1});
                PdfPCell cell = new PdfPCell();
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                cell.setVerticalAlignment(Element.ALIGN_CENTER);
                
                // table headers
                cell.setPhrase(new Phrase("Product", fontTblHead));
                table.addCell(cell);
                cell.setPhrase(new Phrase("Stock in vehical", fontTblHead));
                table.addCell(cell);
                cell.setPhrase(new Phrase("Next Order Qty", fontTblHead));
                table.addCell(cell);
                cell.setPhrase(new Phrase("Aloctd. dispatch", fontTblHead));
                table.addCell(cell);
            
                
                progressbar.setValue(20);
                //List<User> users = getListOfUsers();
                con.connect();
                progressbar.setValue(22);
                //String sql = "CALL dispatch_report('"+last_distribute_proforma_date_first+"','"+last_distribute_proforma_date_last+"','"+next_distribute_proforma_date_first+"','"+next_distribute_proforma_date_last+"');";
                String sql = "CALL bulk_dispatch('"+firstOrderNo+"', '"+lastOrderNo+"');";
                ResultSet rs =  con.query(sql);
                progressbar.setValue(50);
                while(rs.next()){
                    //for(int i=0; i<20; i++){
                    //price=rs.getString("price").split
                    cell.setHorizontalAlignment(Element.ALIGN_LEFT);
                    table.addCell(new Phrase(rs.getString("product_name"),fontTblData));
                    cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
                    //table.addCell(cell);
                    /*cell.setPhrase(new Phrase(String.valueOf(rs.getInt("last_proforma_dispatch")),fontTblData));
                    table.addCell(cell);
                    cell.setPhrase(new Phrase(String.valueOf(rs.getInt("last_invoiced_distribution")),fontTblData));
                    table.addCell(cell);
                    cell.setPhrase(new Phrase(rs.getString("last_invoiced_sale"),fontTblData));
                    table.addCell(cell);*/
                    cell.setPhrase(new Phrase(String.valueOf(rs.getInt("vehicle_stock")),fontTblData));
                    table.addCell(cell);
                    cell.setPhrase(new Phrase(String.valueOf(rs.getInt("qty")),fontTblData));
                    table.addCell(cell);
                    /*cell.setPhrase(new Phrase(rs.getString("next_estimated_sale"),fontTblData));
                    table.addCell(cell);*/
                    cell.setPhrase(new Phrase(String.valueOf(rs.getInt("next_dispatch")),fontTblData));
                    table.addCell(cell);
                    //}
                }
                con.close();
                //doc.open();
                // adding table to document
                doc.add(table);
                progressbar.setValue(95);
            }
            writer.close();  
            
            if (Desktop.isDesktopSupported()) {
                File myFile = new File(DEST);
                Desktop.getDesktop().open(myFile);
            }
            progressbar.setValue(100);
        } catch (DocumentException | FileNotFoundException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
    
    public void reset(){
        /*jdate_NextDistributionFirstDate.setDate(date);
        jdate_NextDistributionLastDate.setDate(date);
        jdate_LastDistributionFirstDate.setDate(date);
        jdate_LastDistributionLastDate.setDate(date);*/
        txt_firstOrderNo.setText("");
        txt_lastOrderNo.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateReport;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JProgressBar progressbar;
    private javax.swing.JTextField txt_firstOrderNo;
    private javax.swing.JTextField txt_lastOrderNo;
    // End of variables declaration//GEN-END:variables
}
